### ISSUE TITLE
Could not create file

### ISSUE THREAD

**Issue by HelixPiano** [SevenChords/CipesAtHome#11]
Using the win64 version of the program. After unzipping it and trying to run it I get the error message
"Could not locate results/4784.txt... This is a bug."

The results folder is created but without any content inside it.
Did I miss anything?

**Comment by malleoz** [comment]
Please verify that you are extracting this program to a directory which does not have write-protection, perhaps somewhere in your Downloads folder. Let me know if the issue persists. Can you also send over the log file?

**Comment by HelixPiano** [comment]
I changed to Downloads and ran as administrator. This works.
