### ISSUE TITLE
Linux build failure

### ISSUE THREAD

**Issue by Quantaly** [SevenChords/CipesAtHome#17]
I tried to build the program on a Raspberry Pi following the instructions in the README and received this error from `make`:

```
/usr/bin/ld: calculator.o: in function `calculateOrder':
calculator.c:(.text+0x3be0): undefined reference to `_itoa'
```

Looking into the issue, I found [this StackOverflow thread](https://stackoverflow.com/questions/190229/where-is-the-itoa-function-in-linux) about how the `itoa` function is nonstandard. I was able to get it to compile by replacing line 2407 of [calculator.c](https://github.com/SevenChords/CipesAtHome/blob/33f7db12417c96544e89d1d64d4b81019e79c20e/calculator.c#L2407) with the following:

```c
sprintf(new_record, "%d", result_cache.frames);
```

There are a few other workarounds mentioned in the thread, but this one seemed like the easiest drop-in replacement. After the change, the program compiled successfully and is now chugging away perfectly well on the Pi.

**Comment by malleoz** [comment]
This has been resolved by switching to fprintf. Thank you!
