### ISSUE TITLE
null response from server

### ISSUE THREAD

**Issue by ISSOtm** [SevenChords/CipesAtHome#22]
Version: compiled directly from `master`, `git describe HEAD --tags` says `1.12-6-g5fc1ed6`

I suddenly got this: `[2020-10-04 17:48:46][Server][Upload][Response][(null)]`

The program hasn't crashed or anything, but this looks like a `NULL` pointer passed to a `printf`-like, which my system prints gracefully, but others crash on. (The C standard specifies that passing `NULL` to `printf` etc.) is UB.)

**Comment by Lego6245** [comment]
There was a bug on the server that would respond with an empty response body in some cases. This has since been fixed.
