### ISSUE TITLE
The "current fastest record" is outdated by several days - says 4036 frames at time of writing

### ISSUE THREAD

**Issue by DimitriPilot3** [SevenChords/CipesAtHome#24]
Running the latest release build (with an internet connection) prints the following:
``The current fastest record is 4036 frames. Happy cooking!``

which, at the time of writing, is outdated and expected to be `3924` frames according to the automated [live leaderboard website](https://github.com/Lego6245/hundoLeaderboard) hosted at https://recipesatho.me/.

Manually visiting the following URL will reproduce the same output of `4036` frames:
https://github.com/SevenChords/CipesAtHome/blob/42253cb691c4714643b39fbb987fd7134bc05c39/FTPManagement.c#L85

@Lego6245 this issue might need your help - maybe i'm in the wrong repo hehe

**Comment by Lego6245** [comment]
The fastest frames record is not updated until manually verified by @malleoz as to not reject records that may be as fast or faster should the fastest be determined to be invalid. This process may take a few days.

**Comment by DimitriPilot3** [comment]
Ah, got it. Thanks for the response.
