### ISSUE TITLE
Support: Setting Select & Randomise both to 0 yields no results?

### ISSUE THREAD

**Issue by MVail88** [SevenChords/CipesAtHome#25]
I've had CipesAtHome running on 8 threads on a reasonably powerful PC since October 4th. I was led to believe that while setting both config options for select and randomise to 0 would yield deterministic results (in other words, the exact same results anyone else running it with these settings would find), it would still yield results of some sort. Thus far though it has been seemingly stuck on about 59 steps currently taken for several days and has gone through 10s of millions of iterations, the count for them overflowing into the negatives over and over again. Not going to lie, I don't 100% understand what the output I see is trying to communicate so I have no idea if it is actually still making some sort of progress or if it has gotten stuck in some sort of loop.

I guess what I'm asking is, do I just need to give it more time still (maybe infinite time), or is something bugged with these settings such that no results will ever be found? Or, am I in fact misinterpreting something and results have been found and just not saved in the "results" folder or displayed on the leaderboard website?

**Comment by riggedCoinflip** [comment]
Setting both to 0 makes your code traverse the same tree over and over.
