### ISSUE TITLE
Inquiry of existence.

### ISSUE THREAD

**Issue by foxsouns** [SevenChords/CipesAtHome#26]
Is this project still running? It's nearly 6 months out of date, I haven't seen any activity from the repo: does this still need people mining for the fastest path, or should I just move on? Are the servers even still up?

**Comment by malleoz** [comment]
@foxsouns This is an incredibly delayed response, so sorry for that. Development on this project will be resuming. We aim to make this program more efficient than it currently is atm. So as of right now we don't expect users to be mining, but we anticipate that we will benefit from users mining in the near future as development progresses.
